apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  selector:
     matchLabels:
       app: sa-logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      imagePullSecrets:
      - name: secret-registry
      containers:
        - image: 166287152401.dkr.ecr.us-west-2.amazonaws.com/sa-logic:v1
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
