apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  restartPolicy: Never
  serviceAccountName: kaniko
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--dockerfile=Dockerfile",
           "--context=`pwd`", 
           "--destination=152742397097.dkr.ecr.us-east-2.amazonaws.com/kaniko-test:latest",
           "--cache=true"           ]
    # command:
    # - /busybox/cat
    # tty: true
  #   volumeMounts:
  #   - name: docker-config
  #     mountPath: "/kaniko/.docker/"
  # volumes:
  # - name: docker-config
  #   configMap:
  #     name: docker-config