apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    # env:
    # - name: AWS_SDK_LOAD_CONFIG
    #   value: true
    volumeMounts:
    - name: aws-secret
      mountPath: /root/.aws/
  volumes:
  - name: aws-secret
    secret:
      secretName: aws-secret