pipeline {
    agent none
    environment {
        IMAGE_NAME   = '166287152401.dkr.ecr.us-west-2.amazonaws.com/sa-logic'
        IMAGE_TAG    = 'v1'
    }
    stages {
        stage('Python-Image-Build') {
            agent {
                node {
                    label 'slave2'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS')
                retry(1) 
            }
            steps {
                echo 'Building Python-App'
                sh   'docker build -f ./sa-logic/Dockerfile -t sa-logic:latest ./sa-logic'
                sh   'docker tag sa-logic:latest ${IMAGE_TAG}:${IMAGE_TAG}'
            }
        }
        stage('Python-Image-Push') {
            agent {
                node {
                    label 'slave2'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                script {
                    sh 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 166287152401.dkr.ecr.us-west-2.amazonaws.com'
                    sh 'docker push ${IMAGE_TAG}:${IMAGE_TAG}'
                    echo 'Image has Pushed!'
                }
                
            }
        }
        stage('Test-Sa-Logic') {
            agent {
                node {
                    label 'slave1'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS')
                retry(1) 
            }
            steps {
                script {
                    sh 'microk8s kubectl apply -f resource-manifests/sa-logic-deployment.yaml -n test'
                    sh 'microk8s kubectl apply -f resource-manifests/service-sa-logic.yaml -n test'
                }                
            }
        }    
    }
}
