pipeline {
    agent {
        node {
            label 'slave2'
        }
    }
    environment {
        APP_NAME = "sa-logic"
        REGION = "us-west-2"
        ECR_URI = "166287152401.dkr.ecr.us-west-2.amazonaws.com"
        REPO_NAME   = 'sa-logic'
    }
    stages {
        stage('Python-Image-Build') {
            
            options {
                timeout(time: 1, unit: 'HOURS')
                retry(1) 
            }
            steps {
                echo 'Building Python-App'
                sh   'sudo docker build -f ./sa-logic/Dockerfile -t ${APP_NAME}:$BUILD_ID ./sa-logic'
                sh   'sudo docker tag   ${APP_NAME}:$BUILD_ID  ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
            }
        }
        stage('Python-Image-Push') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                script {
                    sh   'aws ecr get-login-password --region ${REGION} | sudo docker login --username AWS --password-stdin ${ECR_URI}'
                    sh   'sudo docker push ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
                    echo 'Image has Pushed!'
                }
                
            }
        }  
        stage('Update helm chart Release Version') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            
            steps {                               
                withCredentials([usernamePassword(credentialsId: 'GITHUB', passwordVariable: 'GIT_PASSWD', usernameVariable: 'GIT_USER')]){
                    git credentialsId: 'GITHUB', url: 'https://github.com/AryanRaj750/helm.git'
                    sh """                 
                    sed -i 's/.*sa_logic_version.*/sa_logic_version: v$BUILD_ID/g' Sentiment-Analyser/values.yaml                  
                    git remote set-url origin https://${GIT_PASSWD}@github.com/AryanRaj750/helm.git
                    git add .
                    git commit -m 'new build $BUILD_ID'
                    git push origin master
                    """
                }                      
                
            }
        }        
    }
}
