apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
  labels:
    app: sa-web-app
spec:
  selector:
    matchLabels:
      app: sa-web-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      # imagePullSecrets:
      # - name: {{ .Values.reg_secret }}
      containers:
      - image: "{{ .Values.sa_web_app.image }}:{{ .Values.sa_web_app.version }}" #166287152401.dkr.ecr.us-west-2.amazonaws.com/sa-webapp:v1
        imagePullPolicy: Always
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: {{ .Values.SA_LOGIC_API_URL }}
        ports:
          - containerPort: 8080
