apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2                                             # 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      imagePullSecrets:
      - name: {{ .Values.​reg-secret }}
      containers:
        - image: "{{ .Values.sa-frontend.image }}:{{ .Values.sa-frontend.version }}"
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80