pipeline {
    agent {        
        label 'slave2'        
    } 
    environment {
        APP_NAME = "sa-frontend"
        REGION = "us-west-2"
        ECR_URI = "166287152401.dkr.ecr.us-west-2.amazonaws.com"
        REPO_NAME   = 'sa-frontend'
        USER = "Aryan Raj"
        EMAIL = "Ar9131000@gmail.com"
    }
    stages {
        stage('React-Frontend-Image-Build') {            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                sh '''
                    echo 'Building Front-End React App'
                    webapi=`aws ssm get-parameters --name webapp-url --query Parameters[0] | jq -r .Value`
                    sed  -i 's,http://localhost:8080/sentiment,'$webapi',g' sa-frontend/src/App.js
                    docker build -f ./sa-frontend/Dockerfile -t ${APP_NAME}:v$BUILD_ID ./sa-frontend
                    docker tag ${APP_NAME}:v$BUILD_ID ${ECR_URI}/${REPO_NAME}:v$BUILD_ID
                '''
                
            }
        }   
        stage('React-Frontend-Image-Push') {            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                script {
                    sh   'aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}'
                    sh   'docker push ${ECR_URI}/${REPO_NAME}:v$BUILD_ID'
                    echo 'Image has Pushed!'
                }
                
            }
        }       
        stage('Update helm chart Release Version') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            
            steps {                               
                withCredentials([usernamePassword(credentialsId: 'GITHUB', passwordVariable: 'GIT_PASSWD', usernameVariable: 'GIT_USER')]){
                    git credentialsId: 'GITHUB', url: 'https://github.com/AryanRaj750/helm.git'
                    sh """                 
                    sed -i 's/.*sa_frontend_version.*/sa_frontend_version: v$BUILD_ID/g' Sentiment-Analyser/values.yaml                  
                    git remote set-url origin https://${GIT_PASSWD}@github.com/AryanRaj750/helm.git
                    git add .
                    git config --global user.email ${EMAIL}
                    git config --global user.name ${USER}
                    git commit -m 'new build $BUILD_ID'
                    git push origin master
                    """
                }                      
                
            }
        } 
    }
}
