pipeline {
    agent {
        node {
            label 'slave2'
        }
    }
    environment {
        APP_NAME = "sa-webapp"
        REGION = "us-west-2"
        ECR_URI = "166287152401.dkr.ecr.us-west-2.amazonaws.com"
        REPO_NAME   = 'sa-webapp'
    }
    stages {
        
        stage('Java-WebApp-Image-Build') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                echo 'Building Java-WebApp'
                sh   'sudo docker build -f ./sa-webapp/Dockerfile -t ${APP_NAME}:$BUILD_ID ./sa-webapp'
                sh   'sudo docker tag ${APP_NAME}:$BUILD_ID ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
            }
        }
        stage('Java-WebApp-Image-Push') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                script {
                    sh   'aws ecr get-login-password --region ${REGION} | sudo docker login --username AWS --password-stdin ${ECR_URI}'
                    sh   'sudo docker push ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
                    echo 'Image has Pushed!'
                }
                
            }
        }
        stage('Update helm chart Release Version') {
            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            git credentialsId: 'GITHUB', url: 'https://github.com/AryanRaj750/helm.git'
            steps {
                script {
                    sh   'git clone https://github.com/AryanRaj750/helm.git'
                    sh   "sed -i 's/sa_frontend_version: v1/sa_frontend_version: v$BUILD_ID/g' Sentiment-Analyser/values.yaml"
                    sh   "git add ."
                    sh   "git commit -m 'new build $BUILD_ID'"
                    sh   "git push"
                    echo 'Helm repo updated!'
                }
                
            }
        }        
         
    }
}
