pipeline {
    agent none
    environment {
        APP_NAME = "sa-webapp"
        REGION = "us-west-2"
        ECR_URI = "166287152401.dkr.ecr.us-west-2.amazonaws.com"
        REPO_NAME   = 'sa-webapp'
    }
    stages {
        
        stage('Java-WebApp-Image-Build') {
            agent {
                node {
                    label 'slave2'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                echo 'Building Java-WebApp'
                sh   'sudo docker build -f ./sa-webapp/Dockerfile -t ${APP_NAME}:$BUILD_ID ./sa-webapp'
                sh   'sudo docker tag ${APP_NAME}:$BUILD_ID ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
            }
        }
        stage('Java-WebApp-Image-Push') {
            agent {
                node {
                    label 'slave2'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                script {
                    sh   'aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}'
                    sh   'docker push ${ECR_URI}/${REPO_NAME}:$BUILD_ID'
                    echo 'Image has Pushed!'
                }
                
            }
        }        
         
    }
}
