pipeline {
    agent {        
        label 'slave2'        
    }  
    environment {
        APP_NAME = "sa-webapp"
        REGION = "us-west-2"
        ECR_URI = "166287152401.dkr.ecr.us-west-2.amazonaws.com"
        REPO_NAME   = 'sa-webapp'
        USER = "Aryan Raj"
        EMAIL = "Ar9131000@gmail.com"
    }
    stages {
        
        stage('Java-WebApp-Image-Build') {            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                sh '''
                    echo 'Building Java-WebApp'
                    docker build -f ./sa-webapp/Dockerfile -t ${APP_NAME}:v$BUILD_ID ./sa-webapp
                    docker tag ${APP_NAME}:v$BUILD_ID ${ECR_URI}/${REPO_NAME}:v$BUILD_ID
                '''
            }
        }
        
        stage('Java-WebApp-Image-Push') {            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }
            steps {
                sh '''
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}
                    docker push ${ECR_URI}/${REPO_NAME}:v$BUILD_ID
                    echo 'Image has Pushed!'
                '''
            }
        }

        stage('Update helm chart Release Version') {            
            options {
                timeout(time: 1, unit: 'HOURS') 
                retry(1) 
            }            
            steps {                               
                withCredentials([usernamePassword(credentialsId: 'GITHUB', passwordVariable: 'GIT_PASSWD', usernameVariable: 'GIT_USER')]){
                    git credentialsId: 'GITHUB', url: 'https://github.com/AryanRaj750/helm.git'
                    sh """                 
                        sed -i 's/.*sa_web_app_version.*/sa_web_app_version: v$BUILD_ID/g' Sentiment-Analyser/values.yaml                  
                        git remote set-url origin https://${GIT_PASSWD}@github.com/AryanRaj750/helm.git
                        git add .
                        git config --global user.email ${EMAIL}
                        git config --global user.name ${USER}
                        git commit -m 'new build $BUILD_ID'
                        git push origin master
                    """
                }                      
                
            }
        }        
         
    }
}
